/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coche;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author 100005543.joan23
 */
public class VistaCoche extends javax.swing.JFrame {

    /**
     * Creates new form VistaCoche
     */
    public VistaCoche() {
        initComponents();
        this.err_color.setVisible(false);
        this.err_model.setVisible(false);
        this.err_name.setVisible(false);
        this.err_telf.setVisible(false);
        this.err_select.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_nom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_telf = new javax.swing.JTextField();
        jt_model = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jt_blanco_candy = new javax.swing.JRadioButton();
        jt_rojo_emocion = new javax.swing.JRadioButton();
        jt_gris_zenith = new javax.swing.JRadioButton();
        jt_negro_magico = new javax.swing.JRadioButton();
        jt_rojo_rubi = new javax.swing.JRadioButton();
        jt_verde_natura = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        err_name = new javax.swing.JLabel();
        err_telf = new javax.swing.JLabel();
        err_model = new javax.swing.JLabel();
        err_color = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_generar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        err_select = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("COCHE");

        jLabel3.setText("Nom:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Dades Client");

        jt_nom.setToolTipText("Introduce un nombre");
        jt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nomActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefon:");

        jt_telf.setToolTipText("Introduce un telefono con valor entero");
        jt_telf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_telfKeyTyped(evt);
            }
        });

        jt_model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Altea 1.4 TSI 125CV (92kw) Arena", "Altea 1.9 TDI 105CV (77kw) Arena", "Altea 1.9 TDI 105CV (77kw) DPF DSSG Arena", "Altea 2.0 TDI 140CV (103kw) 6 Vel. Arena", "Altea 2.0 TDI 16V 140CV (103kw) 6 Vel. DSG Arena" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Model");

        buttonGroup1.add(jt_blanco_candy);
        jt_blanco_candy.setSelected(true);
        jt_blanco_candy.setText("Blanco candy");

        buttonGroup1.add(jt_rojo_emocion);
        jt_rojo_emocion.setText("Rojo emoción");

        buttonGroup1.add(jt_gris_zenith);
        jt_gris_zenith.setText("Gris zenith");

        buttonGroup1.add(jt_negro_magico);
        jt_negro_magico.setText("Negro mágico");

        buttonGroup1.add(jt_rojo_rubi);
        jt_rojo_rubi.setText("Rojo rubí");

        buttonGroup1.add(jt_verde_natura);
        jt_verde_natura.setText("Verde natura");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Color");

        jCheckBox1.setText("Instalacion telefono Bluetooth + MP3 + antena antirrobo (8 altavoces en total)");

        jCheckBox2.setText("Conexion USB en apoyabrazos (elimina la conexion AUX-in)");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Conexion iPod en apoyabrazos (elimina la conexion AUX-in)");

        jCheckBox4.setText("Portaobjetos interior en techo");

        jCheckBox5.setText("Asientos calefactado + eyectores calefactados + lavafaros + montante A calefactado (+ retrovisores posicion parking solo en Reference)");

        jCheckBox6.setText("Sistema navegacion blanco y negro + MP3 + antena antirrobo. (elimina la onexion AUX-in)");

        jCheckBox7.setText("SEAT Mediasystem: Sistema de navegacion dinamica con pantalla tactil a color de 6,5''', lector de DD, disco duro de 30GB, conectividad Bluetooth y mandos en el volante. (Incluye DVD con cartografia)");

        jCheckBox8.setText("Airbags laterales posteriores");

        jCheckBox9.setText("Faros Bixenon + AFS");

        err_name.setForeground(new java.awt.Color(204, 0, 0));
        err_name.setText("Añade su nombre");

        err_telf.setForeground(new java.awt.Color(204, 0, 0));
        err_telf.setText("Campo obligatorio y numerico");

        err_model.setForeground(new java.awt.Color(204, 0, 0));
        err_model.setText("Selecciona un modelo");

        err_color.setForeground(new java.awt.Color(204, 0, 0));
        err_color.setText("Selecciona un color");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jButton1.setText("Sortir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        err_select.setForeground(new java.awt.Color(204, 0, 0));
        err_select.setText("Seleccione alguna opcion");

        jLabel9.setText("Opicions");

        jLabel10.setText("TOTAL:");

        jt_total.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(err_model))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_blanco_candy)
                                    .addComponent(jt_rojo_emocion)
                                    .addComponent(jt_gris_zenith))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_negro_magico)
                                    .addComponent(jt_rojo_rubi)
                                    .addComponent(jt_verde_natura)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_telf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(err_telf))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(err_name))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(err_color)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(err_select))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_generar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(err_select)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err_name))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jt_telf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err_telf))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err_model))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_generar)
                            .addComponent(btn_guardar)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(err_color))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_blanco_candy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_rojo_emocion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_gris_zenith))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jt_negro_magico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_rojo_rubi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_verde_natura)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void escribir2(JTextArea area){

 try
 {
  String nombre="";
  JFileChooser file=new JFileChooser();
  file.showSaveDialog(this);
  File guarda =file.getSelectedFile();
 
  if(guarda !=null)
  {
   /*guardamos el archivo y le damos el formato directamente,
    * si queremos que se guarde en formato doc lo definimos como .doc*/
    FileWriter  save=new FileWriter(guarda+".txt");
   // BufferedWriter bw = new BufferedWriter(save); 
    String p=area.getText();
    
      System.out.println(p);
      String [] lineas = p.split("\n");
        System.out.println("Texto original:\n"+p);
        System.out.println("Texto modificado:\n");
        for(int i=0;i<lineas.length;i++){
           
          
          save.write(lineas[i]); 
          save.write(System.getProperty("line.separator"));
        }
    save.write(area.getText());
    save.close();
    JOptionPane.showMessageDialog(null,
         "El archivo se a guardado Exitosamente",
             "Información",JOptionPane.INFORMATION_MESSAGE);
    }
 }
  catch(IOException ex)
  {
   JOptionPane.showMessageDialog(null,
        "Su archivo no se ha guardado",
           "Advertencia",JOptionPane.WARNING_MESSAGE);
  }
 }

    private void jt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nomActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        // TODO add your handling code here:

        this.err_telf.setVisible(false);
        this.err_name.setVisible(false);
        this.err_model.setVisible(false);
        this.err_color.setVisible(false);
        this.err_select.setVisible(false);
        
        if (this.jt_telf.getText().isEmpty()){
            this.err_telf.setVisible(true);
        }
        if (this.jt_nom.getText().isEmpty()){
            this.err_name.setVisible(true);
        }
        
        if (!(this.jCheckBox1.isSelected() || this.jCheckBox2.isSelected() || this.jCheckBox3.isSelected() || this.jCheckBox4.isSelected() || this.jCheckBox5.isSelected() || this.jCheckBox6.isSelected() || this.jCheckBox7.isSelected() || this.jCheckBox8.isSelected() || this.jCheckBox9.isSelected())){
            this.err_select.setVisible(true);
        }

        String n1;
        double num;
        num = 0;
        

        n1 = this.jt_telf.getText();
       
        try {
            num = Double.valueOf(n1);
            int precio = 0;

            String parametro = "";
            parametro = "El nombre es: " + this.jt_nom.getText() + "\n";
            parametro = parametro + "El telefono es: " + this.jt_telf.getText() + "\n";
            parametro = parametro + "Modelo seleccionado: " + this.jt_model.getSelectedItem() + "\n";
            precio=precio+21452;
            
            if (jt_blanco_candy.isSelected()) {
                parametro = parametro + "El color es: Blanco candy \n";
            precio=precio+0;
            } else if (jt_rojo_emocion.isSelected()) {
                parametro = parametro + "El color es: Rojo emecion \n";
            precio=precio+152;
            } else if (jt_gris_zenith.isSelected()) {
                parametro = parametro + "El color es: Gris zenith \n";
            precio=precio+400;
            } else if (jt_negro_magico.isSelected()) {
                parametro = parametro + "El color es: Negro magico \n";
            precio=precio+400;
            } else if (jt_rojo_rubi.isSelected()) {
                parametro = parametro + "El color es: Rojo rubi \n";
            precio=precio+400;
            } else if (jt_verde_natura.isSelected()) {
                parametro = parametro + "El color es: Verde natura \n";
            precio=precio+276;
            }
            parametro = parametro + "Opciones seleccionadas: \n";
            if (jCheckBox1.isSelected()) {
                parametro = parametro + "- Instalacion telefono Bluetooth + MP3 + antena antirrobo (8 altavoces en total) \n";
                precio=precio+400;
            }
            if (jCheckBox2.isSelected()) {
                parametro = parametro + "- Conexion USB en apoyabrazos (elimina la conexion AUX-in) \n";
            precio=precio+100;
            }
            if (jCheckBox3.isSelected()) {
                parametro = parametro + "- Conexion iPod en apoyabrazos (elimina la conexion AUX-in) \n";
            precio=precio+100;
            }
            if (jCheckBox4.isSelected()) {
                parametro = parametro + "- Portaobjetos interior en techo \n";
            precio=precio+98;
            }
            if (jCheckBox5.isSelected()) {
                parametro = parametro + "- Asientos calefactado + eyectores calefactados + lavafaros + montante A calefactado (+ retrovisores posicion parking solo en Reference) \n";
            precio=precio+581;
            }
            if (jCheckBox6.isSelected()) {
                parametro = parametro + "- Sistema navegacion blanco y negro + MP3 + antena antirrobo. (elimina la onexion AUX-in) \n";
            precio=precio+1070;
            }
            if (jCheckBox7.isSelected()) {
                parametro = parametro + "- SEAT Mediasystem: Sistema de navegacion dinamica con pantalla tactil a color de 6,5''', lector de DD, disco duro de 30GB, conectividad Bluetooth y mandos en el volante. (Incluye DVD con cartografia) \n";
            precio=precio+1465;
            }
            if (jCheckBox8.isSelected()) {
                parametro = parametro + "- Airbags laterales posteriores \n";
            precio=precio+253;
            }
            if (jCheckBox9.isSelected()) {
                parametro = parametro + "- Faros Bixenon + AFS \n";
            precio=precio+835;
            }
            
            this.jt_total.setText(String.valueOf(precio));
            
            parametro = parametro + "Precio total: "+precio;
            this.jTextArea1.setText(parametro);

        } catch (Exception e) {
            // this.err_telf.setVisible(true);
            // this.err_name.setVisible(true);            
            // this.jt_telf.setText("");
            // this.err_name.setText("");
        }


    }//GEN-LAST:event_btn_generarActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jt_nom.setText("");
        this.jt_telf.setText("");
        this.jt_blanco_candy.setSelected(true);
        this.jCheckBox1.setSelected(false);
        this.jCheckBox2.setSelected(false);
        this.jCheckBox3.setSelected(false);
        this.jCheckBox4.setSelected(false);
        this.jCheckBox5.setSelected(false);
        this.jCheckBox6.setSelected(false);
        this.jCheckBox7.setSelected(false);
        this.jCheckBox8.setSelected(false);
        this.jCheckBox9.setSelected(false);
        this.jTextArea1.setText("");
        
        this.err_telf.setVisible(false);
        this.err_name.setVisible(false);
        this.err_model.setVisible(false);
        this.err_color.setVisible(false);
        this.err_select.setVisible(false);
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        escribir2(this.jTextArea1);
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jt_telfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_telfKeyTyped
        // TODO add your handling code here:
        
        char numtelf = evt.getKeyChar();
        if (( numtelf <'0' || numtelf>'9')) evt.consume();
        if(jt_telf.getText().length()>=9 ) evt.consume();
        if (Character.isLetter(numtelf)) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Solo se puede introducir numeros");
            
        }
    }//GEN-LAST:event_jt_telfKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCoche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel err_color;
    private javax.swing.JLabel err_model;
    private javax.swing.JLabel err_name;
    private javax.swing.JLabel err_select;
    private javax.swing.JLabel err_telf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton jt_blanco_candy;
    private javax.swing.JRadioButton jt_gris_zenith;
    private javax.swing.JComboBox<String> jt_model;
    private javax.swing.JRadioButton jt_negro_magico;
    private javax.swing.JTextField jt_nom;
    private javax.swing.JRadioButton jt_rojo_emocion;
    private javax.swing.JRadioButton jt_rojo_rubi;
    private javax.swing.JTextField jt_telf;
    private javax.swing.JTextField jt_total;
    private javax.swing.JRadioButton jt_verde_natura;
    // End of variables declaration//GEN-END:variables
}
